version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: takeat_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: takeat
    ports:
      - '5432:5432'
    volumes:
      - takeat_pgdata:/var/lib/postgresql/data

volumes:
  takeat_pgdata:
